version: '3'
services:
  frontend:
    image: myfront
    container_name: frontend
    ports:
      - 3001:80
    networks:
      - frontend
  backend:
    image: con1 
    container_name: backend
    restart: unless-stopped
    ports:
      - 8005:8001
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
